name: Image
on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
jobs:
  build:
    name: Build and push image to registry
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Set current branch name
        id: get-branch-name
        shell: bash
        run: |
          echo "branch_name=${GITHUB_BASE_REF#/refs/heads/}" >> $GITHUB_OUTPUT
        env:
          GITHUB_BASE_REF: ${{ github.event.base_ref }}

      - name: Set up QEMU
        id: setup-qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: set-up-docker-buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Yandex Cloud Container Registry
        id: login-to-yc
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

#      - name: Build and push staging or prod
#        id: build-and-push-stable
#        if: github.ref_name != 'dev'
#        uses: docker/build-push-action@v3
#        with:
#          push: true
#          #cache-from: type=registry,ref=cr.yandex/${{ secrets.DOCKER_REGISTRY_ID }}/${{ inputs.service }}:${{ steps.get-branch-name.outputs.branch_name }}-cache
#          #cache-to: type=inline
#          tags: cr.yandex/${{ secrets.DOCKER_REGISTRY_ID }}/${{ inputs.service }}:${{ github.ref_name }}
#          #, cr.yandex/${{ secrets.DOCKER_REGISTRY_ID }}/${{ inputs.service }}:${{ steps.get-branch-name.outputs.branch_name }}-cache

      - name: Build and push dev
        id: build-and-push-dev
        if: github.ref_name == 'add-kubernetes-config'
        uses: docker/build-push-action@v3
        with:
          push: true
          #cache-from: type=registry,ref=cr.yandex/${{ secrets.DOCKER_REGISTRY_ID }}/${{ inputs.service }}:dev-cache
          #cache-to: type=inline
          tags: cr.yandex/${{ secrets.DOCKER_REGISTRY_ID }}/${{ inputs.service }}:dev.${{ github.sha }}
          #, cr.yandex/${{ secrets.DOCKER_REGISTRY_ID }}/${{ inputs.service }}:${{ steps.get-branch-name.outputs.branch_name }}-cache

      - name: notify to slack
        id: notify-to-slack
        uses: act10ns/slack@master
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
